### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by joelmukuthu** [fastify/fastify-helmet#107]
## 🚀 Feature Proposal

Please consider releasing a new version of fastify-helmet to update dependency versions. In particular, to bump fastify-plugin to v3.

## Motivation

To remove the "fastify not found, proceeding anyway" log messages.

## Example

N/A

**Comment by salmanm** [comment]
Released [v5.1.0](https://github.com/fastify/fastify-helmet/releases/tag/v5.1.0)
