### ISSUE TITLE
Documentation is lacking

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify-helmet#13]
I am attempting to add this to an application and I really don't have any idea how to configure it. For example, if I want to set the `hsts` maximum age to 30 minutes, how do I do that? This plugin needs documentation on how to configure it.

**Comment by delvedor** [comment]
Pr? :)

**Comment by jsumners** [comment]
How does one write documentation that he needs to understand how to use something?

**Comment by delvedor** [comment]
Just take a look to the code :)

Example of passing an option to `x-powered-by` middleware:
```js
fastify.register(
  require('fastify-helmet'),
  { hidePoweredBy: { setTo: 'PHP 4.2.0' } }
)
```
