### ISSUE TITLE
TypeError: Cannot read property 'setHeader' of undefined

### ISSUE THREAD

**Issue by InstanceOfMichael** [fastify/fastify-helmet#135]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

2.15.3

### Plugin version

1.6.1

### Node.js version

v15.12.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Linux drip20 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux

### Description

fastify-helmet throws `TypeError: Cannot read property 'setHeader' of undefined`

![Capture](https://user-images.githubusercontent.com/4094542/122684056-5044fa80-d1d1-11eb-931f-d37da2e3a759.PNG)

### Steps to Reproduce

1. brand new app using https://www.npmjs.com/package/create-fastify-app
2. yarn add fastify-helmet
3. register fastify-helmet in accordance to docs
4. Any HTTP request will print `TypeError: Cannot read property 'setHeader' of undefined` and crash the server with no further stack information.

**Comment by simoneb** [comment]
`create-fastify-app` is not an officially supported way to create a fastify application. I suspect the issue you came across may be related to that. Can you please share a reproducible example or try to create a new application manually instead? If the problem goes away, then the issue it in `create-fastify-app`

**Comment by climba03003** [comment]
As you are using `fastify@2`, it is just version mismatch. `fastify@2` do not provide `request.raw` and `reply.raw` syntax like `fastify@3`.

Please use `fastify-helmet@3` for `fastify@2`.
