### ISSUE TITLE
How to disable helmet contentSecurityPolicy for specific reply? Or disable helmet?

### ISSUE THREAD

**Issue by mariusa** [fastify/fastify-helmet#161]
## 💬  Question here 

Hi, need to disable helmet contentSecurityPolicy for a few specific replies:
```
    if (someCondition) { disable contentSecurityPolicy }
    reply.type('text/html') //otherwise it's plain text, instead of being interpreted as html
    reply.send(page) //this has a <script> which doesn't execute due to contentSecurityPolicy
```

helmet is added with `register()`, part of app.js, launched using fastify-cli
```js
 fastify.register(helmet)
```

Found these, but didn't figure out a solution:
https://github.com/helmetjs/helmet/wiki/Conditionally-using-middleware

https://www.fastify.io/docs/latest/Reference/Middleware/#restrict-middleware-execution-to-certain-paths
(not using fastify.use(), but  fastify.register())

https://github.com/fastify/fastify-helmet/issues/89

Tried also
```js
//still uses helmet
    reply.raw.writeHead(200, { 'Content-Type': 'text/html' }) 
    reply.raw.write(page)
     reply.raw.end()
```
Thanks!

- *node version*: 16
- *fastify version*: 3
- *fastify-helmet*: 4

**Comment by mariusa** [comment]
I'd like to try. 
Once this is implemented, how would the user code look?


**option 1: inside request handler, depending on condition**
```js
fastify.get('/some-route', , async (req, reply) => {
if (someCondition) { 
  //disable helmet only for this specific reply
  reply.middleware.unregister('helmet') // don't think this is possible?
}
reply.send('done')
})
```

Could
https://www.fastify.io/docs/latest/Reference/Reply/#hijack
or 
https://www.fastify.io/docs/latest/Reference/Reply/#server
be used?

**option 2: enable helmet (any middleware) only for specific routes**
how would the user code look?

Which option do you recommend? 2. is good enough and seems simpler

**Comment by mcollina** [comment]
The 1 you have described is not possible as the helmet is applied during the `'onRequest'` hook. 

2 is already possible, see my snippet above.

What is missing is a way to say:

```js
app.register(require('fastify-helmet'), {
  hook: false // does not register the onRequest hook
})

app.get('/', async (req, reply) => {
  if (something) {
    await reply.helmet()
  }
})
```

**Comment by darkgl0w** [comment]
Hello.

I will give it a go. I have an almost ready PR that should cover this use case ^^

If my schedule don't change I should be able to submit it today :)

**Comment by darkgl0w** [comment]
Draft PR published.
It needs a bit of polish but early reviews are highly welcome.

This PR will introduce 2 new options :
- An option to define when registering the package: `global` that can be `undefined`, `true` or `false` (by default when it is not set by the user it is `true`)
- A new shorthand route option: `helmet` that can be set to `false` to disable helmet on a specific route or `an helmet configuration object` that will be merged with (and take precedence over) the global options if needed.

There should be no breaking change.

**Comment by mariusa** [comment]
Just tested `Use case number 2`, works great, thank you!
