### ISSUE TITLE
Headers not set on error thrown from fastify-bearer-auth

### ISSUE THREAD

**Issue by Fdawgs** [fastify/fastify-helmet#168]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.25.3

### Plugin version

7.0.0

### Node.js version

16.13.2

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

On upgrading from 6.0.0 to 7.0.0, the helmet headers are no longer present in the error response returned by [fastify/fastify-bearer-auth](https://github.com/fastify/fastify-bearer-auth).

### Steps to Reproduce

Stand up server instance with both `fastify-helmet` and `fastify-bearer-auth` registered to the server:

```js
const fastify = require("fastify")();

// Import plugins
const helmet = require("fastify-helmet");
const bearer = require("fastify-bearer-auth");

/**
 * @description test function
 */
async function server() {
	fastify
		.register(helmet)
		.register(bearer, { keys: new Set(["a-super-secret-key1"]) })
		.route({
			method: "GET",
			url: "/foo",
			handler: (req, res) => {
				res.send("ok");
			},
		});
	await fastify.listen({ port: 8000 });
}

server();
```

Make a GET request with an invalid bearer token:
```
> GET /foo HTTP/1.1
> Host: localhost:8000
> User-Agent: insomnia/2021.7.2
> Authorization: Bearer a-super-secret-key12
> Accept: */*
```

Response:
```
< HTTP/1.1 401 Unauthorized
< content-type: application/json; charset=utf-8
< content-length: 40
< Date: Mon, 17 Jan 2022 14:48:36 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
```

### Expected Behavior

Response of:

```
< HTTP/1.1 401 Unauthorized
< Content-Security-Policy: default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests
< Cross-Origin-Embedder-Policy: require-corp
< Cross-Origin-Opener-Policy: same-origin
< Cross-Origin-Resource-Policy: same-origin
< X-DNS-Prefetch-Control: off
< Expect-CT: max-age=0
< X-Frame-Options: SAMEORIGIN
< Strict-Transport-Security: max-age=15552000; includeSubDomains
< X-Download-Options: noopen
< X-Content-Type-Options: nosniff
< Origin-Agent-Cluster: ?1
< X-Permitted-Cross-Domain-Policies: none
< Referrer-Policy: no-referrer
< X-XSS-Protection: 0
< content-type: application/json; charset=utf-8
< content-length: 40
< Date: Mon, 17 Jan 2022 14:58:22 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
```

**Comment by mcollina** [comment]
I don't think this approach is viable and we should revert the last few PR as we should apply the hook to the error handler as well as the not found handler.

As an alternative to a full revert, we can put the per-route check behind an option, disabled by default.

cc @darkgl0w I don't think this is fixable in the current approach.

**Comment by darkgl0w** [comment]
@Fdawgs @mcollina > switching from an `onRequest` hook to an `onSend` hook should solve this problem.

You can take a look here : https://github.com/darkgl0w/fastify-helmet/tree/rework-branch
the CI run: https://github.com/darkgl0w/fastify-helmet/actions/runs/1709873763

Now I must figure how to apply the headers to the not found handler (I think that's the only case that's not covered here.

WDYT ?

**Comment by climba03003** [comment]
> @Fdawgs @mcollina > switching from `onRequest` to `onSend` should fix this problem.
> 
> You can take a look here : https://github.com/darkgl0w/fastify-helmet/tree/rework-branch the CI run: https://github.com/darkgl0w/fastify-helmet/actions/runs/1710100841
> 
> Now I must figure how to apply the headers to the not found handler (that's the only case that's not covered here).
> 
> WDYT ?
> 
> A benchmark run (this seems to be a bit more performant than the actual branch) :
> 
> ```shell
> npx autocannon -W [-c 100 -d 30 -p 10] -c 100 -d 30 -p 10 localhost:3000
> Running 30s warmup @ http://localhost:3000
> 100 connections with 10 pipelining factor
> 
> Running 30s test @ http://localhost:3000
> 100 connections with 10 pipelining factor
> 
> ┌─────────┬───────┬───────┬───────┬───────┬──────────┬──────────┬────────┐
> │ Stat    │ 2.5%  │ 50%   │ 97.5% │ 99%   │ Avg      │ Stdev    │ Max    │
> ├─────────┼───────┼───────┼───────┼───────┼──────────┼──────────┼────────┤
> │ Latency │ 26 ms │ 50 ms │ 78 ms │ 91 ms │ 51.91 ms │ 12.96 ms │ 148 ms │
> └─────────┴───────┴───────┴───────┴───────┴──────────┴──────────┴────────┘
> ┌───────────┬─────────┬─────────┬───────┬───────┬──────────┬────────┬─────────┐
> │ Stat      │ 1%      │ 2.5%    │ 50%   │ 97.5% │ Avg      │ Stdev  │ Min     │
> ├───────────┼─────────┼─────────┼───────┼───────┼──────────┼────────┼─────────┤
> │ Req/Sec   │ 16119   │ 16119   │ 19103 │ 20255 │ 19074.54 │ 744.32 │ 16119   │
> ├───────────┼─────────┼─────────┼───────┼───────┼──────────┼────────┼─────────┤
> │ Bytes/Sec │ 15.2 MB │ 15.2 MB │ 18 MB │ 19 MB │ 17.9 MB  │ 699 kB │ 15.2 MB │
> └───────────┴─────────┴─────────┴───────┴───────┴──────────┴────────┴─────────┘
> 
> Req/Bytes counts sampled once per second.
> 
> 573k requests in 30.03s, 538 MB read
> ```

I don't think it is still suitable for using the current approach (modifying the route option). It will cause problem in either way.

I would go for `routeOption.config`, so it can pass the configuration to `request.context.config`. And we can decide the behavior inside a single whatever hook.

**Comment by mcollina** [comment]
I agree with @climba03003

**Comment by darkgl0w** [comment]
> Unrelated comment: I think we should expose the original route option inside the request.context, it is much more simple and do not need to rely on a additional layer request.context.config.

That would be a huge feature and it will make a bunch of things way more straightforward to implement. :heart:
