### ISSUE TITLE
hidePoweredBy flag doesnt work

### ISSUE THREAD

**Issue by Sergei8888** [fastify/fastify-helmet#173]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.4

### Plugin version

7.0.1

### Node.js version

v16.13.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

21H1

### Description

```
server.register(helmetPlugin, {
    hidePoweredBy: true,
});
```

makes no effect. There is always 'x-powered-by: Express' header in all requests

### Steps to Reproduce

Run your plugin and try

### Expected Behavior

'x-powered-by: Express' header must gone when hidePoweredBy is true

**Comment by jsumners** [comment]
This is a Fastify plugin. Express should not be a factor.

**Comment by Sergei8888** [comment]
I know that it is fastify plugin but for some reason this plugin sends 'x-powered-by: Express' header

**Comment by jsumners** [comment]
No where in this repository is "powered-by" referenced in code -- https://github.com/fastify/fastify-helmet/search?q=powered-by&type=code

Nor is there any code within the Fastify organization that references "powered-by" -- https://github.com/search?q=org%3Afastify+powered-by&type=code

Please provide a minimal reproduction that exhibits this issue.

**Comment by Sergei8888** [comment]
Headers were from poxy server
