### ISSUE TITLE
Reference error when using bitbucket pipelines

### ISSUE THREAD

**Issue by permpkin** [fastify/fastify-helmet#20]
Reference `require('./config')` at "./index.js:4" does not default to "config.json" and instead results in failing on... `Cannot find module './config' from 'index.js'`

appending ".json" to "config" fixes the issue.

**Comment by scottty881** [comment]
I am also coming across this issue when I compile with typescript.  Any tricks/hints to get it to work? From what I can tell, the compiler is not copying over the config.json file when it runs.

"typescript": "^2.9.2"
"fastify-helmet": "^1.0.3"

**Comment by mcollina** [comment]
Can you please provide an example of what you are trying to achieve?

**Comment by permpkin** [comment]
Transpiling using typescript references `./config` incorrectly using default settings, appending ".json" to the reference fixes the issue. ( or adding `"resolveJsonModule": true` in `compilerOptions` )
