### ISSUE TITLE
Error when building project after setting `moduleResolution: "Node16"`

### ISSUE THREAD

**Issue by p-kuen** [fastify/fastify-helmet#208]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.10.0

### Plugin version

10.0.2

### Node.js version

19.0.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

Ventura 13.0

### Description

I recently switched my project's `tsconfig` to use `moduleResolution: "Node16"`, because I was forced to do that (Got ```TS1452: 'resolution-mode' assertions are only supported when `moduleResolution` is `node16` or `nodenext`.```)

After switching I get the following message when using fastify-helmet:
```
node_modules/.pnpm/@fastify+helmet@10.0.2/node_modules/@fastify/helmet/types/index.d.ts:2:62 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("helmet")' call instead.

2 import helmet, { contentSecurityPolicy, HelmetOptions } from 'helmet';
                                                               ~~~~~~~~


Found 1 error in node_modules/.pnpm/@fastify+helmet@10.0.2/node_modules/@fastify/helmet/types/index.d.ts:2
```

This is one of two packages where I had problems with switching. To be honest, I do not have an idea what's the problem here, ESM is still a bit of a blackbox for me.
Even when dynamically importing the package, this error still exists.

Update: In my tests, setting `type: "module"` in package.json of `fastify-helmet` resolves the issue, but I do not know if this has other unwanted side-effects.

### Steps to Reproduce

1. Create a new typescript project
2. Use `moduleResolution: "Node16"` in `tsconfig.json`
3. Ensure that `skipLibCheck` is *not* `true`
4. Add `@fastify/helmet` as a dependency
5. Import the dependency: `import helmet from "@fastify/helmet"`
6. Build using latest `typescript` (currently 4.9.3)

**Comment by climba03003** [comment]
Support still on progress.
Refs https://github.com/fastify/fastify/issues/4349
