### ISSUE TITLE
Used in the nestjs (typescript) framework, the ts compiler tells you that the types do not match

### ISSUE THREAD

**Issue by ufec** [fastify/fastify-helmet#209]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.10.2

### Plugin version

10.1.0

### Node.js version

16.17.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

Windows 11

### Description

Used in the nestjs (typescript) framework, the ts compiler tells you that the types do not match
![image](https://user-images.githubusercontent.com/34962267/203954995-5fd609d2-6d3b-4de1-b7de-6a7aa7f51f7d.png)
as shown in the picture
I have to use type assertion like this
```ts
type FastifyAdapterParameters = Parameters<typeof adapter.register>;
type FastifyAdapterRegister = FastifyAdapterParameters[0];
const Helmet = fastifyHelmet as unknown as FastifyAdapterRegister;
await app.register(Helmet); // or await adapter.register(Helmet);
```
If I don't do this, I will get a type validation error

> Argument of type 'FastifyHelmet' is not assignable to parameter of type 'FastifyPluginCallback<FastifyHelmetOptions, RawServerDefault, FastifyTypeProviderDefault> | FastifyPluginAsync<...> | Promise<...> | Promise<...>'.
  Type 'FastifyHelmet' is not assignable to type 'FastifyPluginCallback<FastifyHelmetOptions, RawServerDefault, FastifyTypeProviderDefault>'.

### Steps to Reproduce

```shell
npm i -g @nestjs/cli
nest new test_helmet
cd test_helmet
npm uninstall @nestjs/platform-express && npm install --save @nestjs/platform-fastify fastify @fastify/helmet
```
modify `src/main.ts` to
```ts
import { NestFactory } from '@nestjs/core';
import {
  FastifyAdapter,
  NestFastifyApplication,
} from '@nestjs/platform-fastify';
import fastifyHelmet from '@fastify/helmet';
import { AppModule } from './app.module';

async function bootstrap() {
  const adapter = new FastifyAdapter();
  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    adapter,
  );
  app.register(fastifyHelmet);
  await app.listen(3000);
}
bootstrap();
```
you will get a type error
![image](https://user-images.githubusercontent.com/34962267/203959696-e15e6572-dc65-4ac9-a584-9834b969e613.png)

### Expected Behavior

like readme to run

**Comment by mcollina** [comment]
Thanks for reporting. We do not have the resources to support Nest.js users. Please refer to the Nest [Discord](discord.gg/NestJS) channel (support) for such questions.

**Comment by kibertoad** [comment]
@ufec isn't that a nestjs integration issue that should be resolved on nestjs ecosystem side?

**Comment by Uzlopak** [comment]
Can you prepare a repo, where we can simply clone it and see if we can do something?

**Comment by Uzlopak** [comment]
I think I could reproduce it. It is maybe an issue with the typings from nestjs, as the register-typings are different then our fastify typings for the register call.

**Comment by Uzlopak** [comment]
I reopen it, as there potentially some issues independent from nest.js

**Comment by Uzlopak** [comment]
I found a potential different bug. I think the issue here is in nest.js. Closing this Issue. I suggest to open a ticket in nest.js

**Comment by ufec** [comment]
@Uzlopak Ok, I just created a demo of Fastify TypeScript, it is indeed a problem with the nestjs platform, thanks to the Fastify team for the timely response, I think Fastify is very cool
