### ISSUE TITLE
Use nonces for inline script sources

### ISSUE THREAD

**Issue by dbauszus-glx** [fastify/fastify-helmet#22]
Is there any working example how to use nonces for inline script sources?

I had a look at the [example on the helmet website](https://helmetjs.github.io/docs/csp) but I fail to enable this with the fastify-helmet  plugin.

**Comment by mcollina** [comment]
Can you please post an example? You should be able to do:


```
fastify.register(require('fastify-helmet'), {
  scriptSrc: [
      "'self'",
      function (req, res) {
        return "'nonce-" + res.locals.nonce + "'"  // 'nonce-614d9122-d5b0-4760-aecf-3a5d17cf0ac9'
      }
    ]
})
```
