### ISSUE TITLE
Using Fastify 4.23.0 get deprecated "request.routeConfig" warnings

### ISSUE THREAD

**Issue by pgbross** [fastify/fastify-helmet#229]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.23.0

### Plugin version

11.0.0

### Node.js version

20.3.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Fedora 39

### Description

With Fastify 4.23.0 get `[FSTDEP016] FastifyDeprecation: You are accessing the deprecated "request.routeConfig" property. Use "request.routeOptions.config" instead. Property "req.routeConfig" will be removed in `fastify@5` warnings.

This arises in `fastify.addHook('onRequest'...) where it looks for helmet specific config on the route.

Applying the suggested change in the deprecation warning eliminates the warning.

### Steps to Reproduce

Simply require the `@fastify/helmet` plugin and observe the server messages in a terminal console.

### Expected Behavior

No deprecation warnings.

**Comment by Eomm** [comment]
Thanks for reporting!
Would you like to send a Pull Request to address this issue?

**Comment by pgbross** [comment]
> Thanks for reporting! Would you like to send a Pull Request to address this issue?

Sure - done in #230

**Comment by sefakpsz** [comment]
There is any solution to fix the error. Can you give any solution to fix this error ?

**Comment by sefakpsz** [comment]
I didn't work for me at first but try again to install it with "--save-dev".

**Comment by Eomm** [comment]
This issue is 1yo. Please open a new detailed issue adding a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).
