### ISSUE TITLE
Use of `if(typeof value !== 'undefined')`?

### ISSUE THREAD

**Issue by Fdawgs** [fastify/fastify-helmet#236]
Noticed this in a few places in this repo:

https://github.com/fastify/fastify-helmet/blob/b0aacaee932e1629a6233c97424d739735b3293c/index.js#L25C31-L25C31

Never seen this before, does this have a performance benefit over the following?:
- `if(value)`
- `if(value !== undefined)`

**Comment by Uzlopak** [comment]
More like differenciating between null and undefined.

**Comment by Fdawgs** [comment]
@gurgunday will make PRs and point them back to this issue.
