### ISSUE TITLE
6 deprecated subdependencies found

### ISSUE THREAD

**Issue by 0x0bit** [fastify/fastify-helmet#248]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

10.3.9

### Plugin version

11.1.1

### Node.js version

20.14.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.5

### Description

![image](https://github.com/fastify/fastify-helmet/assets/23352300/1c9f2c50-271c-475c-8962-877c494146db)

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue?

**Comment by MrYbo** [comment]
> 感谢报告！您想发送 Pull 请求来解决此问题吗？

yes, of course
