### ISSUE TITLE
Support for Http2 out of the box for the helmet plugin

### ISSUE THREAD

**Issue by vijayakumar-psg587** [fastify/fastify-helmet#68]
## 🚀 Feature Proposal
The current helmet plugin takes in the middleware with HttpServer, req and response. As we move towards Http2, could I propose the plugin to accept both http and http2 depending upon the protocol set by default while creating fastify?
## Motivation
The reason for asking a proposal is to make sure that it supports modern protocol.

**Comment by Eomm** [comment]
Would you like to send a PR to archive this feature? 💪

**Comment by vijayakumar-psg587** [comment]
Hi @Eomm  . I am unsure if I will be able to contribute to the new feature if I raise a pull request. Currently my workload is pretty heavy. I am sure it will take months before I can contribute. Any other alternatvices/suggestions?

**Comment by rabin999** [comment]
@vijayakumar-psg587  you can add

```
app.addHook('onSend', (request, reply, payload, done) => {
        reply.header('header', 'value')
        done()
    })
```

to set security header, for reference you can also lusca

**Comment by Eomm** [comment]
@vijayakumar-psg587 do you have a helmet config example?
So it will be clear the target and perhaps, with this input, somebody will take care of it 🥇

**Comment by rabin999** [comment]
I am on the same path for middleware support on http2, since fastify ts module is tightly coupled It's hard to write all code again to support http2. If I could then I will make PR for that.

**Comment by vijayakumar-psg587** [comment]
Apologies for the delayed response. @rabin999 thank you. I created my own version of all middlewares that helmet offers. Hence thought if this comes as a part of fastify-helmet out of the box, it will be very useful. Again since I am held up pretty much with the deliverables, I am unable to find enough time to work on this.
