### ISSUE TITLE
Why this plugin is most appropriate than helmet ?

### ISSUE THREAD

**Issue by nacimgoura** [fastify/fastify-helmet#7]
Hello,
i have a question.
If we use fastify, why should we use this plugin instead of helmet native ?
thanks you !

**Comment by mcollina** [comment]
Because helmet spawns an express application and attach all the middlewares there. This just adds all the middlewares to fastify itself, and so it is significantly faster.

**Comment by nacimgoura** [comment]
Okay, thank you for your answer :smile:
