### ISSUE TITLE
Unwanted disabling of other security modules due to incorrect early return

### ISSUE THREAD

**Issue by huycan** [fastify/fastify-helmet#79]
Hi guys,

The bug happens at this line:

https://github.com/fastify/fastify-helmet/blob/8a789b4a21f2d9b1cfc901e14d900ee0266b3a35/index.js#L31

I arrived here from your Fastify Plugin Guide to see how a plugin should be written, and intended to install the package for my app.

After reading your code and cross-checking your previous commits, I believe the intention here is to disable a particular middleware if its name is set to false in the plugin option.

The "return" in the line of code above will disable all subsequent plugins too. This bug is probably a consequence of moving from

```javascript
middlewares.forEach(function () {
...
return;
...
})
```

to

```javascript
for (const middleware of middlewares) {
...
return; // should be "continue;"
...
}
```

Please close this issue if I get your intention wrong!

Thanks and cheers!

**Comment by mcollina** [comment]
Good spot! Would you like to send a PR to fix this? Please add a unit test so we don’t regress.

**Comment by huycan** [comment]
Sorry, I am busy at the moment! Just stopped by to inform you guys!

Thanks for quick response!
