### ISSUE TITLE
Remove HPKP 

### ISSUE THREAD

**Issue by lu-zen** [fastify/fastify-helmet#83]
## 🚀 Feature Proposal

Consider the removal of HPKP middleware from fastify-helmet.

## Motivation
Browsers are dropping HPKP security features¹²³. Helmetjs will drop this middleware in the next major release.

[Remove hpkp from "mainline" Helmet](https://github.com/helmetjs/helmet/issues/180)
[HTTP Public Key Pinning (HPKP)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Public_Key_Pinning)

¹ [Firefox 72 for Developers](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/72#Security)
² [Remove HTTP-Based Public Key Pinning (removed) ](https://www.chromestatus.com/feature/5903385005916160)
³ [consider removal of HTTP Public Key Pinning (HPKP)](https://bugzilla.mozilla.org/show_bug.cgi?id=1412438)

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by lu-zen** [comment]
@mcollina Sure.
Do you think that is useful to keep a warning for current users or someone who tries to use it or just remove it right away?
