### ISSUE TITLE
Broken types in v5

### ISSUE THREAD

**Issue by mfpopa** [fastify/fastify-helmet#92]
## 🐛 Bug Report

@mcollina @EvanHahn The types are broken in `fastify-hemlet@v5` in the sense that the options neither come up via IntelliSense, nor can one manually specify them because TypeScript throws the following error: `Object literal may only specify known properties, and 'hidePoweredBy' does not exist in type '(RegisterOptions & FastifyHelmetOptions) | (() => RegisterOptions & FastifyHelmetOptions)'.ts(2769)
`

The issue is this line: https://github.com/helmetjs/helmet/blob/master/index.ts#L26 because the `HelmetOptions` interface is not exported which means [this import](https://github.com/fastify/fastify-helmet/blob/master/index.d.ts#L2) resolves to nothing.

It should say `export interface HelmetOptions`. If it's not exported, it cannot be picked up by `fastify-helmet`.

**Comment by fox1t** [comment]
There is already a PR that resolves this: https://github.com/fastify/fastify-helmet/pull/91
There is no need for `helmet` to export that types in order to be conusmed and exported by `fastify-helmet`

**Comment by EvanHahn** [comment]
Looks like #91 resolves this, but I'm happy to help if I'm needed further.

**Comment by mfpopa** [comment]
Ah, should've checked the pull requests. Yeah, that fixes the issue... quite neatly I should say.
