### ISSUE TITLE
Error building project after Updating fasitfy-helmet to latest version 5.0.1

### ISSUE THREAD

**Issue by gp187** [fastify/fastify-helmet#94]
## 🐛 Bug Report

Updating `fasitfy-helmet` to latest version `5.0.1`

## To Reproduce

```js
  // -->Register: security policy and plugins
  fastify.register(require('fastify-helmet'), {
    hidePoweredBy: {
      setTo: 'PHP 7.4.0'
    }
  });
```

## Expected behavior

Throws this error

```js
node_modules/fastify-helmet/index.d.ts:2:8 - error TS1259: Module '"/lab/naologic-apps/bee11/node_modules/helmet/dist/index"' can only be default-imported using the 'esModuleInterop' flag

2 import helmet from "helmet";
         ~~~~~~

  node_modules/helmet/dist/index.d.ts:44:1
    44 export = helmet;
       ~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.

```

Cannot just enable `esModuleInterop` because it will trigger errors in many other modules.

## Your Environment

- *node version*: 12
- *fastify version*: 3.4.0
- *os*: Linux

**Comment by mcollina** [comment]
What version of fastify-plugin have you got in your tree? Can you please include a full example (maybe a repo) to reproduce? thanks

**Comment by fox1t** [comment]
As far as I can see this is not an error. We still use old export here (not the "infamous triplet"). You have 4 options: set the skipLibCheck to true; set esModuleIntrop to true; import using import * as helmet from; send a PR to fix the exports :)

**Comment by mcollina** [comment]
@fox1t we should have the infamous triplet here as well ;)

**Comment by fox1t** [comment]
Yea, I agree. :)

**Comment by fox1t** [comment]
I am going to fix this. It is a problem also on how we import helmet types. 

Thanks for reporting this!
